import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";
import { SidebarProvider } from "@/context/SidebarContext";
import Sidebar from "@/components/navbar/Sidebar";
import Navbar from "@/components/navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <SidebarProvider>
            <Navbar transparent={false} />
            <div className="flex min-h-screen">
              {/* Sidebar burada sabit kalacak, sayfa değiştikçe re-render olmayacak */}
              <Sidebar />

              {/* main alanı kalan tüm genişliği (flex-1) dolduracak ve sayfalar burada açılacak */}
              <main className="flex-1 min-w-0">{children}</main>
            </div>
          </SidebarProvider>
        </UserProvider>
      </body>
    </html>
  );
}
